name: Validate MAIN

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  validate:

    name: Validate Release Candidate

    runs-on: ubuntu-latest

    environment: dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI
        run: databricks --version

      - name: Validate DAB for DEV
        run: databricks bundle validate -t dev

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}